"""empty message

Revision ID: 26250c78d1ac
Revises: 
Create Date: 2026-09-07 16:27:54.845909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26250c78d1ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
