"""Initial schema for Milestone 1 persistence layer

Revision ID: 84d740a5539c
Revises: 
Create Date: 2026-09-08 15:11:19.983105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d740a5539c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.String(length=50), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('officer_id', sa.String(length=100), nullable=False),
    sa.Column('officer_role', sa.String(length=50), nullable=False),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.Column('assigned_by_role', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('previous_assignment_id', sa.String(length=50), nullable=True),
    sa.Column('ended_at', sa.String(length=50), nullable=True),
    sa.Column('ended_by', sa.String(length=100), nullable=True),
    sa.Column('ended_by_role', sa.String(length=50), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_assignments_case_reference'), 'assignments', ['case_reference'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('case_reference', sa.String(length=50), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('object_id', sa.String(length=50), nullable=True),
    sa.Column('previous_state', sa.String(length=50), nullable=True),
    sa.Column('new_state', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('authorization_context', sa.Text(), nullable=True),
    sa.Column('rule_code', sa.String(length=50), nullable=True),
    sa.Column('legal_reference', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_reference'), 'audit_events', ['case_reference'], unique=False)
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=True)
    op.create_table('case_dockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=13), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('incident_date', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('interview_id', sa.String(length=100), nullable=True),
    sa.Column('registered_at', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('statements', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_dockets_case_reference'), 'case_dockets', ['case_reference'], unique=True)
    op.create_index(op.f('ix_case_dockets_citizen_id'), 'case_dockets', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_case_dockets_status'), 'case_dockets', ['status'], unique=False)
    op.create_table('disciplinary_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplinary_case_id', sa.String(length=50), nullable=False),
    sa.Column('source_case_reference', sa.String(length=50), nullable=False),
    sa.Column('escalation_id', sa.String(length=50), nullable=True),
    sa.Column('implicated_officer_id', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_by_role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinary_cases_disciplinary_case_id'), 'disciplinary_cases', ['disciplinary_case_id'], unique=True)
    op.create_index(op.f('ix_disciplinary_cases_source_case_reference'), 'disciplinary_cases', ['source_case_reference'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escalation_id', sa.String(length=50), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_by_role', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('reviewer_role', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('decision_by', sa.String(length=100), nullable=True),
    sa.Column('decision_by_role', sa.String(length=50), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decision_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_case_reference'), 'escalations', ['case_reference'], unique=False)
    op.create_index(op.f('ix_escalations_escalation_id'), 'escalations', ['escalation_id'], unique=True)
    op.create_table('evidence_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=50), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.String(length=50), nullable=True),
    sa.Column('storage_reference', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=200), nullable=True),
    sa.Column('integrity_status', sa.String(length=50), nullable=True),
    sa.Column('chain_of_custody_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_index_evidence_id'), 'evidence_index', ['evidence_id'], unique=True)
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.String(length=100), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_by_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolution_information', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_case_reference'), 'flags', ['case_reference'], unique=False)
    op.create_index(op.f('ix_flags_flag_id'), 'flags', ['flag_id'], unique=True)
    op.create_table('freezes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freeze_id', sa.String(length=50), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('related_escalation_id', sa.String(length=50), nullable=True),
    sa.Column('frozen_at', sa.String(length=50), nullable=True),
    sa.Column('released_at', sa.String(length=50), nullable=True),
    sa.Column('released_by', sa.String(length=100), nullable=True),
    sa.Column('released_by_role', sa.String(length=50), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freezes_case_reference'), 'freezes', ['case_reference'], unique=False)
    op.create_index(op.f('ix_freezes_freeze_id'), 'freezes', ['freeze_id'], unique=True)
    op.create_table('integrity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integrity_event_id', sa.String(length=50), nullable=False),
    sa.Column('subject_event_id', sa.String(length=50), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('case_reference', sa.String(length=50), nullable=True),
    sa.Column('integrity_status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrity_events_integrity_event_id'), 'integrity_events', ['integrity_event_id'], unique=True)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.String(length=100), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=13), nullable=True),
    sa.Column('constable_id', sa.String(length=13), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('start_timestamp', sa.String(length=50), nullable=True),
    sa.Column('completion_timestamp', sa.String(length=50), nullable=True),
    sa.Column('citizen_recording', sa.JSON(), nullable=True),
    sa.Column('constable_recording', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_case_reference'), 'interviews', ['case_reference'], unique=False)
    op.create_index(op.f('ix_interviews_interview_id'), 'interviews', ['interview_id'], unique=True)
    op.create_table('investigation_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(length=50), nullable=False),
    sa.Column('investigation_id', sa.String(length=50), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('detective_id', sa.String(length=100), nullable=True),
    sa.Column('finding_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('is_final_outcome', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_findings_finding_id'), 'investigation_findings', ['finding_id'], unique=True)
    op.create_index(op.f('ix_investigation_findings_investigation_id'), 'investigation_findings', ['investigation_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.String(length=50), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=False),
    sa.Column('detective_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('final_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_case_reference'), 'investigations', ['case_reference'], unique=False)
    op.create_index(op.f('ix_investigations_investigation_id'), 'investigations', ['investigation_id'], unique=True)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.String(length=100), nullable=False),
    sa.Column('interview_id', sa.String(length=100), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=True),
    sa.Column('recorder_id', sa.String(length=100), nullable=True),
    sa.Column('recorder_role', sa.String(length=50), nullable=True),
    sa.Column('recording_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('storage_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_interview_id'), 'recordings', ['interview_id'], unique=False)
    op.create_index(op.f('ix_recordings_recording_id'), 'recordings', ['recording_id'], unique=True)
    op.create_table('related_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.String(length=200), nullable=False),
    sa.Column('source_case_reference', sa.String(length=50), nullable=False),
    sa.Column('related_case_reference', sa.String(length=50), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_by_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_cases_related_case_reference'), 'related_cases', ['related_case_reference'], unique=False)
    op.create_index(op.f('ix_related_cases_relationship_id'), 'related_cases', ['relationship_id'], unique=True)
    op.create_index(op.f('ix_related_cases_source_case_reference'), 'related_cases', ['source_case_reference'], unique=False)
    op.create_table('review_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(length=50), nullable=False),
    sa.Column('escalation_id', sa.String(length=50), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.Column('author_role', sa.String(length=50), nullable=True),
    sa.Column('finding_type', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_escalation_id'), 'review_findings', ['escalation_id'], unique=False)
    op.create_index(op.f('ix_review_findings_finding_id'), 'review_findings', ['finding_id'], unique=True)
    op.create_table('review_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.String(length=50), nullable=False),
    sa.Column('escalation_id', sa.String(length=50), nullable=False),
    sa.Column('case_reference', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.Column('author_role', sa.String(length=50), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_notes_escalation_id'), 'review_notes', ['escalation_id'], unique=False)
    op.create_index(op.f('ix_review_notes_note_id'), 'review_notes', ['note_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=13), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('access_state', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_test_id'), 'users', ['test_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_test_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_review_notes_note_id'), table_name='review_notes')
    op.drop_index(op.f('ix_review_notes_escalation_id'), table_name='review_notes')
    op.drop_table('review_notes')
    op.drop_index(op.f('ix_review_findings_finding_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_escalation_id'), table_name='review_findings')
    op.drop_table('review_findings')
    op.drop_index(op.f('ix_related_cases_source_case_reference'), table_name='related_cases')
    op.drop_index(op.f('ix_related_cases_relationship_id'), table_name='related_cases')
    op.drop_index(op.f('ix_related_cases_related_case_reference'), table_name='related_cases')
    op.drop_table('related_cases')
    op.drop_index(op.f('ix_recordings_recording_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_interview_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_investigations_investigation_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_case_reference'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_investigation_findings_investigation_id'), table_name='investigation_findings')
    op.drop_index(op.f('ix_investigation_findings_finding_id'), table_name='investigation_findings')
    op.drop_table('investigation_findings')
    op.drop_index(op.f('ix_interviews_interview_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_case_reference'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_integrity_events_integrity_event_id'), table_name='integrity_events')
    op.drop_table('integrity_events')
    op.drop_index(op.f('ix_freezes_freeze_id'), table_name='freezes')
    op.drop_index(op.f('ix_freezes_case_reference'), table_name='freezes')
    op.drop_table('freezes')
    op.drop_index(op.f('ix_flags_flag_id'), table_name='flags')
    op.drop_index(op.f('ix_flags_case_reference'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_evidence_index_evidence_id'), table_name='evidence_index')
    op.drop_table('evidence_index')
    op.drop_index(op.f('ix_escalations_escalation_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_case_reference'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_disciplinary_cases_source_case_reference'), table_name='disciplinary_cases')
    op.drop_index(op.f('ix_disciplinary_cases_disciplinary_case_id'), table_name='disciplinary_cases')
    op.drop_table('disciplinary_cases')
    op.drop_index(op.f('ix_case_dockets_status'), table_name='case_dockets')
    op.drop_index(op.f('ix_case_dockets_citizen_id'), table_name='case_dockets')
    op.drop_index(op.f('ix_case_dockets_case_reference'), table_name='case_dockets')
    op.drop_table('case_dockets')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_reference'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assignments_case_reference'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
